branch-defaults:
  aws-prod:
    environment: br-web-backend-prod
    group_suffix: null
global:
  application_name: betterreads-web-backend
  branch: null
  default_ec2_keyname: taylor-betterreads
  default_platform: Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
